# Generated by Django 5.1.7 on 2025-04-25 20:28

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_departement', models.CharField(help_text='Entrez le nom du département', max_length=250, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Nom du département')),
                ('description', models.TextField(blank=True, help_text='Description détaillée du département', null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Département',
                'verbose_name_plural': 'Départements',
                'ordering': ['nom_departement'],
            },
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_etudiant', models.CharField(help_text="Entrez le nom de l'étudiant", max_length=250, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Nom')),
                ('prenom_etudiant', models.CharField(help_text="Entrez le prénom de l'étudiant", max_length=250, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Prénom')),
                ('date_naissance', models.DateField(help_text='Sélectionnez la date de naissance', verbose_name='Date de naissance')),
                ('email', models.EmailField(help_text="Entrez l'adresse email de l'étudiant", max_length=254, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='Email')),
                ('adresse', models.CharField(blank=True, help_text="Entrez l'adresse complète de l'étudiant", max_length=500, null=True, verbose_name='Adresse')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
                ('departement', models.ForeignKey(blank=True, help_text="Sélectionnez le département de l'étudiant", null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.departement', verbose_name='Département')),
            ],
            options={
                'verbose_name': 'Étudiant',
                'verbose_name_plural': 'Étudiants',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['nom_etudiant', 'prenom_etudiant'], name='webapp_etud_nom_etu_2d79de_idx'), models.Index(fields=['email'], name='webapp_etud_email_49564a_idx')],
            },
        ),
    ]
